# To run:
# $ docker-compose up --detach

version: '3'

networks:
  nginx-php-network:

services:
  docker-php-fpm:
    build:
      context: ./docker-php-fpm
    tty: true
    volumes:
      - ./backend-app:/var/www
    networks:
      - nginx-php-network

  docker-nginx:
    build:
      context: ./docker-nginx
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - docker-php-fpm
    volumes:
      - ./backend-app:/var/www
      - ./docker-nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx-php-network

